openapi: 3.0.3
info:
  title: OpenAPI schema for Walrus template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where resources will be created.
          default: walrus-system
          x-walrus-ui:
            group: Basic
            order: 1
        domain_name:
          title: Domain Name
          type: string
          description: Domain name.
          default: dev.domain.com
          x-walrus-ui:
            group: Basic
            order: 2
        issuer_name:
          title: Issuer Name
          type: string
          description: Origin issuer name
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 3
        issuer_kind:
          title: Issuer Kind
          type: string
          description: Origin issuer kind
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 4
      x-walrus-ui:
        groupOrder:
        - Basic
