openapi: 3.0.3
info:
  title: OpenAPI schema for template Walrus
components:
  schemas:
    variables:
      type: object
      required:
      - password
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: The Kubernetes namespace where the resources will be created.
          default: walrus-system
          x-walrus-ui:
            group: Basic
            order: 2
        host:
          title: Host
          type: string
          description: The host for the database connection.
          default: walrus.yourdomain.com
          x-walrus-ui:
            group: Basic
            order: 3
        username:
          title: Username
          type: string
          description: The username for the database connection.
          default: admin
          x-walrus-ui:
            group: Basic
            order: 4
        password:
          title: Password
          type: string
          description: The password for the database connection.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 5
        issuer:
          title: Issuer
          type: string
          description: The name of the issuer used by Cert-Manager to issue the certificate.
          default: origin-ca-issuer-hv
          x-walrus-ui:
            group: Basic
            order: 6
        issuer_kind:
          title: Issuer Kind
          type: string
          description: The kind of issuer used by Cert-Manager, such as ClusterIssuer
            or other custom issuers.
          default: OriginIssuer
          x-walrus-ui:
            group: Basic
            order: 7
        issuer_group:
          title: Issuer Group
          type: string
          description: The group of the issuer, which organizes different CRDs like
            the ones from Cloudflare.
          default: cert-manager.k8s.cloudflare.com
          x-walrus-ui:
            group: Basic
            order: 8
        ingress_class_name:
          title: Ingress Class Name
          type: string
          description: The name of the ingress class to be used for routing traffic.
            Typically specifies the type of ingress controller, like nginx or traefik.
          default: nginx
          x-walrus-ui:
            group: Basic
            order: 9
        secret_name:
          title: Secret Name
          type: string
          description: The name of the Kubernetes secret that stores the TLS certificate
            for the Walrus ingress.
          default: walrus-yourdomain-com
          x-walrus-ui:
            group: Basic
            order: 10
      x-walrus-ui:
        groupOrder:
        - Basic
